name: deep3dfr
channels:
  - conda-forge
  - pytorch
  - 1adrianb
dependencies:
  - python=3.7
  - tensorflow-gpu=1.13
  - numpy
  - scipy
  - pytorch=1.3.1
  - cudatoolkit
  - face_alignment
  - pip
  - pip:
    # - mesh_renderer
    - opencv-python
    - pillow
